name: Data Update

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 0 * * 0'  # Runs sundays at midnight

jobs:
  fetch-and-process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          pip install pandas pyarrow fastparquet geopandas shapely scikit-learn requests

      - name: Fetch raw data
        run: python scripts/data_fetching.py

      - name: Run data cleaning script
        run: python scripts/data_processing.py

      - name: Commit and push processed data
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/certificats.parquet data/labels.json
          git commit -m "Update processed data"
          git push
        continue-on-error: true  # Prevents failure if no changes have been made
